name: 'Kemocade VRC Group Tracker Action'
description: 'GitHub Action for automatically tracking Group information from the VRChat API'
branding:
  icon: globe
  color: blue
inputs:
  workspace:
    description: 'The workspace directory.'
    default: '/github/workspace'
  output:
    description: 'The directory to write output inside of (relative to workspace). Example, "path/to/output".'
    required: true
  username:
    description: 'VRChat Username'
    required: true
  password:
    description: 'VRChat Password'
    required: true
  key:
    description: 'VRChat 2FA secret key'
    required: true
  shortcode:
    description: 'Desired VRChat Group Shortcode'
    required: true
  discriminators:
    description: 'Desired VRChat Group Discriminators'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-w'
  - ${{ inputs.workspace }}
  - '-o'
  - ${{ inputs.output }}
  - '-u'
  - ${{ inputs.username }}
  - '-p'
  - ${{ inputs.password }}
  - '-k'
  - ${{ inputs.key }}
  - '-g'
  - ${{ inputs.groups }}